title: NosoLab Documentation
description: Everything there is to know about NosoLab
theme: just-the-docs

url: https://docs.nosolab.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
